#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
workflow="$root/.github/workflows/arthur-theme-candidate.yml"
lock="$root/config/arthur-theme.lock"
quickstart_lock="$root/config/istore-quickstart.lock"

fail() { echo "ARTHUR_THEME_GATE: FAIL -- $*" >&2; exit 1; }

[[ -f "$workflow" ]] || fail 'theme candidate workflow is missing'
[[ -f "$lock" ]] || fail 'theme provenance lock is missing'
[[ -f "$quickstart_lock" ]] || fail 'official QuickStart provenance lock is missing'
grep -Fxq 'ISTORE_QUICKSTART_LUCI_REF="8aa8467aabe86f1cf8d23fdb6b0cdd2ef14d2449"' "$quickstart_lock" || fail 'official QuickStart LuCI ref is not frozen'
grep -Fxq 'ISTORE_QUICKSTART_REF="0c789dc2b88f684476f6174201105da6ca6f5133"' "$quickstart_lock" || fail 'official QuickStart service ref is not frozen'
grep -Fxq 'ISTORE_QUICKSTART_LUCI_LICENSE="Apache-2.0"' "$quickstart_lock" || fail 'official QuickStart LuCI license is not recorded'
grep -Fxq 'ISTORE_QUICKSTART_LICENSE="GPL-3.0-only"' "$quickstart_lock" || fail 'official QuickStart service license is not recorded'
grep -Fxq 'ARGON_REF="136eb5d42f30554e89cc737fd90f503909810660"' "$lock" || fail 'Argon ref is not frozen'
grep -Fxq 'KUCAT_REF="82ddd7e4196887089c43af19d4552cd54fa414d2"' "$lock" || fail 'Kucat ref is not frozen'
grep -Fq 'luci-theme-argon' "$workflow" || fail 'Argon package is absent'
grep -Fq 'luci-theme-kucat' "$workflow" || fail 'Kucat package is absent'
grep -Fq './tests/test-argon-default-theme.sh' "$workflow" || fail 'Argon factory-default regression test is not run by the workflow'
grep -Fq 'cd "$SDK_DIR" && ./scripts/feeds update luci' "$workflow" || fail 'SDK LuCI feed update does not run from the SDK root'
grep -Fq 'SDK_LUCI_FEED_MISSING' "$workflow" || fail 'SDK LuCI feed missing gate is absent'
grep -Fq 'feeds/luci/luci.mk' "$workflow" || fail 'SDK luci.mk gate is absent'
grep -Fq 'LUCI_FEED_COMMIT' "$workflow" || fail 'LuCI feed provenance is absent'
grep -Fq 'mkdir -p repository-staging' "$workflow" || fail 'ImageBuilder package staging directory is not prepared'
! grep -Fq 'mkdir -p "$IB_DIR/repositories"' "$workflow" || fail 'ImageBuilder repository configuration path is used as a staging directory'
grep -Fq 'IMAGEBUILDER_PACKAGE_MISSING' "$workflow" || fail 'ImageBuilder required-package gate is absent'
grep -Fq 'required_ib_packages=(argon luci-theme-kucat luci-i18n-base-zh-cn ucode-mod-math)' "$workflow" || fail 'ImageBuilder required package set is not limited to accepted candidate packages'
! grep -Fq 'required_ib_packages=(argon luci-theme-kucat luci-i18n-base-zh-cn wget)' "$workflow" || fail 'ImageBuilder requires an unstaged, non-requested wget package'
grep -Fq 'mkndx ' "$workflow" || fail 'ImageBuilder package index must use explicit apk mkndx validation'
! grep -Fq 'make -C "$IB_DIR" package_index' "$workflow" || fail 'ImageBuilder package index must not hide apk errors behind make package_index'
grep -Fq 'realpath "$IB_DIR/staging_dir/host/bin/apk"' "$workflow" || fail 'ImageBuilder apk path must be absolute before changing directories'
grep -Fq 'make -C "$IB_DIR" _check_keys' "$workflow" || fail 'ImageBuilder local APK signing keys are not prepared before indexing'
grep -Fq -- '--keys-dir "$IB_DIR/keys" --sign "$IB_DIR/keys/local-private-key.pem"' "$workflow" || fail 'ImageBuilder package index is not signed with its local key'
grep -Fq 'CONFIG_LUCI_LANG_zh_Hans=y' "$workflow" || fail 'locked Chinese LuCI translation is not enabled as a boolean SDK symbol'
grep -Fq 'scripts/feeds install luci-base' "$workflow" || fail 'locked LuCI base package is not installed through the SDK feed mechanism'
grep -Fq 'SDK_LUCI_BASE_FEED_PACKAGE_MISSING' "$workflow" || fail 'SDK LuCI base package presence gate is absent'
grep -Fq 'scripts/feeds update base' "$workflow" || fail 'locked ImmortalWrt base feed is not prepared for ucode headers'
grep -Fq 'scripts/feeds install -p base ucode' "$workflow" || fail 'SDK ucode package is not installed from the locked base feed'
grep -Fq 'SDK_UCODE_FEED_PACKAGE_MISSING' "$workflow" || fail 'SDK ucode feed package presence gate is absent'
grep -Fq 'package/feeds/base/ucode/compile' "$workflow" || fail 'SDK ucode package is not compiled before LuCI'
grep -Fq 'UCODE_HEADER=PASS' "$workflow" || fail 'ucode header staging gate is absent'
grep -Fq 'UCODE_STAGING=PASS' "$workflow" || fail 'ucode library staging gate is absent'
grep -Fq 'UCODE_COMMIT' "$workflow" || fail 'ucode provenance is absent'
grep -Fq 'package/feeds/luci/lucihttp/compile' "$workflow" || fail 'liblucihttp-ucode preflight compile is absent'
grep -Fq 'SDK_DEPENDENCY_CLOSURE=PASS' "$workflow" || fail 'SDK dependency closure gate is absent'
defconfig_line="$(grep -nF 'make -C "$SDK_DIR" defconfig' "$workflow" | cut -d: -f1 | head -n1)"
ucode_compile_line="$(grep -nF 'package/feeds/base/ucode/compile' "$workflow" | cut -d: -f1 | head -n1)"
lucihttp_compile_line="$(grep -nF 'package/feeds/luci/lucihttp/compile' "$workflow" | cut -d: -f1 | head -n1)"
test -n "$defconfig_line" && test -n "$ucode_compile_line" && test "$defconfig_line" -lt "$ucode_compile_line" || fail 'ucode compile runs before SDK defconfig'
test "$defconfig_line" -lt "$lucihttp_compile_line" || fail 'lucihttp preflight runs before SDK defconfig'
grep -Fq 'immortalwrt.git\$#' "$workflow" || fail 'base feed sed anchor does not escape the shell $# expansion'
! grep -Fq 'immortalwrt.git$#' "$workflow" || fail 'base feed sed anchor still expands the shell $# token'
grep -Fq 'CONFIG_PACKAGE_liblucihttp-lua=n' "$workflow" || fail 'SDK translation lane still enables the unnecessary Lua lucihttp variant'
grep -Fq 'package/feeds/luci/luci-base/compile' "$workflow" || fail 'locked LuCI base translation package is not compiled by the SDK'
grep -Fq -- "-name 'luci-i18n-base-zh-cn-*.apk'" "$workflow" || fail 'Chinese LuCI package is not staged for ImageBuilder'
grep -Fq "LUCI_DEPENDS:=+wget +curl +jsonfilter" "$workflow" || fail 'Kucat dependency audit target is absent'
grep -Fq "sed -i '/^LUCI_DEPENDS:=+wget +curl +jsonfilter\$/d'" "$workflow" || fail 'Kucat offline-only dependency reduction is absent'
grep -Fq 'name: Candidate Verification' "$workflow" || fail 'candidate firmware verification step is absent'
grep -Fq 'CANDIDATE_VERIFICATION_FAILED_LINE=' "$workflow" || fail 'candidate verification failure-line diagnostic is absent'
grep -Fq 'CANDIDATE_VERIFICATION_FAILED_COMMAND=' "$workflow" || fail 'candidate verification failure-command diagnostic is absent'
grep -Fq 'test -f "$rootfs/etc/init.d/network"' "$workflow" || fail 'network init script verification is absent'
grep -Fq 'test -f "$rootfs/etc/init.d/firewall"' "$workflow" || fail 'firewall init script verification is absent'
grep -Fq 'actions/upload-artifact@v4' "$workflow" || fail 'candidate artifact upload is absent'
grep -Fq 'THEME_CANDIDATE_READY' "$workflow" || fail 'candidate readiness marker is absent'
grep -Fq '97-xinzhao-luci-defaults' "$workflow" || fail 'deterministic LuCI first-boot defaults are absent'
[[ -f "$root/files/etc/uci-defaults/98-xinzhao-web-stack" ]] || fail 'deterministic HTTP web-stack defaults are absent'
grep -Fq 'generate-plugin-i18n-baseline.py' "$workflow" || fail 'plugin zh-cn baseline discovery is absent'
grep -Fq 'PLUGIN_I18N_INCLUDED' "$workflow" || fail 'plugin zh-cn inclusion gate is absent'
grep -Fq 'XZ_ICON_SOURCE=PASS' "$workflow" || fail 'XZ icon source gate is absent'
grep -Fq 'BUILD_INFO_PRESENT=PASS' "$workflow" || fail 'build info gate is absent'
grep -Fq 'luci-i18n-adguardhome-zh-cn' "$workflow" || fail 'AdGuard Home zh-cn package gate is absent'
grep -Fq 'nas-packages-luci.git' "$workflow" || fail 'official QuickStart LuCI source is absent from the candidate workflow'
grep -Fq 'nas-packages.git' "$workflow" || fail 'official QuickStart service source is absent from the candidate workflow'
grep -Fq 'ISTORE_QUICKSTART_LUCI_REF' "$workflow" || fail 'official QuickStart LuCI ref is absent from the candidate workflow'
grep -Fq 'ISTORE_QUICKSTART_REF' "$workflow" || fail 'official QuickStart service ref is absent from the candidate workflow'
branding="$root/files/www/luci-static/xinzhao/branding.js"
[[ -f "$branding" ]] || fail 'branding runtime override is missing'
grep -Fq 'window.location.pathname' "$branding" || fail 'branding metadata does not inspect the actual LuCI status route'
grep -Fq 'status' "$branding" || fail 'branding metadata must retain status route compatibility'
grep -Fq 'object-fit:contain' "$branding" || fail 'sidebar logo must use contain sizing'
grep -Fq 'white-space:nowrap' "$branding" || fail 'sidebar brand text must not wrap'
grep -Fq 'xz-brand-logo' "$workflow" || fail 'theme templates must mark the responsive XZ logo element'
grep -Fq 'for package in luci-i18n-base-zh-cn argon luci-theme-kucat luci-app-openclash' "$workflow" || fail 'candidate package verification uses the wrong Argon package name'
! grep -Fq 'for package in luci-i18n-base-zh-cn luci-theme-argon' "$workflow" || fail 'candidate package verification still expects a non-existent luci-theme-argon package'
! grep -Eq 'curl[[:space:]]+-k|--insecure|Client-ID' "$workflow" || fail 'workflow contains insecure online-theme logic'
! grep -Eq 'make world|FULL_BUILD' "$workflow" || fail 'workflow contains prohibited full build'
echo 'ARTHUR_THEME_GATE: PASS'
